---
apiVersion: v1
kind: Service
metadata:
  name: shopservice-service
spec:
  ports:
    - name: standard
      port: 5135
      targetPort: 8080
  selector:
    app: shopservice
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopservice
  template:
    metadata:
      labels:
        app: shopservice
    spec:
      automountServiceAccountToken: false
      containers:
        - name: shopservice
          image: danielkjr/shopservice:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: secretPath
              value: /run/secrets/jwtSecret
          volumeMounts:
            - name: jwt-secret
              mountPath: /run/secrets
          ports:
            - containerPort: 8080
      volumes:
        - name: jwt-secret
          secret:
            secretName: jwt-secret
       

