apiVersion: v1
kind: Service
metadata:
  name: gameserverregistry
spec:
  type: LoadBalancer  
  ports:
    - name: gameserverregistry
      port: 5229
      targetPort: 8080
  selector:
    app: gameserverregistry
  


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserverregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameserverregistry
  template:
    metadata:
      labels:
        app: gameserverregistry
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gameserverregistry
          image: danielkjr/gameserverregistry:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: secretPath
              value: /run/secrets/jwtSecret
          volumeMounts:
            - name: jwt-secret
              mountPath: /run/secrets
          ports:
            - containerPort: 8080
      volumes:
        - name: jwt-secret
          secret:
            secretName: jwt-secret

---