trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
# Access the secret from the library
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'secret.txt'  # This must match the name of the file in the library

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Set the path to the secret file as an environment variable
- script: |
    echo ##vso[task.setvariable variable=secretPath]$(Agent.TempDirectory)\secret.txt
  displayName: 'Set secretPath environment variable'
  
# Copy the secret file to the working directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'secret.txt'
    TargetFolder: '$(Build.SourcesDirectory)'  # Adjust this as needed for your project structure
