trigger:
- main

resources:
- repo: self

variables:
  tag: "userservice:latest"  # Using a valid tag

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'
    repository: 'userservice'
    
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'userservice'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

