trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Download the secret file
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'secret.txt'  # Ensure this is the name in your pipeline library

# Set the environment variable for secretPath
- script: |
    echo ##vso[task.setvariable variable=secretPath]$(Agent.TempDirectory)\secret.txt
  displayName: 'Set secretPath environment variable'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


