trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'  # Ensure it's a valid tag (which it is)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/UserService/UserService/Dockerfile'
        tags: |
          userservice:$(tag)  # Tagging the image correctly
        
    - task: Docker@2
      displayName: Push to docker
      inputs:
        containerRegistry: 'Docker'  # Ensure this is your service connection name
        repository: 'userservice'    # Ensure it's lowercase and valid
        command: 'push'
        tags: |
          userservice:$(tag)  # Pushing the same tagged image
