trigger:
- main

resources:
- repo: self

variables:
  imageName: "danielkjr/userservice"  # Correct repository with Docker Hub username
  tag: "latest"  # Define tag separately

steps:

# Step 1: Build and Push the Docker image
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'  # Your registered Docker Hub service connection
    repository: '$(imageName)'  # Reference the correct image name
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(imageName):$(tag)'  # Correctly tag the image
