trigger:
- main

resources:
- repo: self

variables:
  tag: "danielkjr/userservice:latest"  # Using a valid tag

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'userservice'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

